spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crss_metering
    username: crss_metering
    password: crss_metering
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 20
  rabbitmq:
#    TODO: Need to finalize username/password
    username: guest
    password: guest

server:
  port: 8084
  undertow:
    accesslog:
      dir: target
      enabled: true
      pattern: combined
  compression:
    enabled: true
    min-response-size: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #    healthcheck:
      #      enabled: true
#    lease:
#      duration: 5
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8082/oauth/access_token
      userAuthorizationUri: http://localhost:8082/oauth/authorize
      clientId: crss
      clientSecret: crsssecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
      access-token-validity-seconds: 3600
    resource:
      userInfoUri: http://localhost:8082/user

logging:
  level:
    com.pemc: DEBUG
    com.netflix: WARN
    org.springframework.cloud: WARN


# TODO: Transfer to spring cloud config
---
spring:
  profiles: psql
mq:
  manifest:
    header: >
      INSERT INTO TXN_MQ_MANIFEST_HEADER (header_id, transaction_id, msp_id, file_count, category,
      upload_by, upload_datetime) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?, ?)
    trailer: >
      UPDATE TXN_MQ_MANIFEST_HEADER SET tail_received = 'Y' WHERE transaction_id = ?
    file: >
      INSERT INTO TXN_MQ_MANIFEST_FILE (file_id, header_id, transaction_id, filename, filetype,
      filesize, checksum) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?, ?)
  meter:
    daily: >
      INSERT INTO TXN_METER_DATA_DAILY (METER_DATA_ID, FILE_ID, SEIN, READING_DATETIME,
      KWD, KWHD, KVARHD, KWR, KWHR, KVARHR, VAN, VBN, VCN, IAN, IBN, ICN, PF, ESTIMATION_FLAG, VERSION)
      VALUES(NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    monthly: >
      INSERT INTO TXN_METER_DATA_MONTHLY (METER_DATA_ID, FILE_ID, SEIN, READING_DATETIME,
      KWD, KWHD, KVARHD, KWR, KWHR, KVARHR, VAN, VBN, VCN, IAN, IBN, ICN, PF, ESTIMATION_FLAG, VERSION)
      VALUES(NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
bcq:
  manifest: >
    INSERT INTO TXN_BCQ_UPLOAD_FILE (FILE_ID, TRANSACTION_ID, FILE_NAME, FILE_SIZE, STATUS, SUBMITTED_DATE)
    VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?)
  data: >
    INSERT INTO TXN_BCQ_DATA (BCQ_DATA_ID, FILE_ID, SELLING_MTN, BUYING_PARTICIPANT_ID, REFERENCE_MTN, START_TIME,
    END_TIME, BCQ) VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?, ?, ?)


---
spring:
  profiles: orcl
mq:
  manifest:
    header: >
      INSERT INTO TXN_MQ_MANIFEST_HEADER (header_id, transaction_id, msp_id, file_count, category,
      upload_by, upload_datetime) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, ?, ?, ?, ?, ?, ?)
    trailer: >
      UPDATE TXN_MQ_MANIFEST_HEADER SET tail_received = 'Y' WHERE transaction_id = ?
    file: >
      INSERT INTO TXN_MQ_MANIFEST_FILE (file_id, header_id, transaction_id, filename, filetype,
      filesize, checksum) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, ?, ?, ?, ?, ?, ?)
  meter:
    # TODO: Include channel and interval status
    daily: >
      INSERT INTO TXN_METER_DATA_DAILY (METER_DATA_ID, FILE_ID, SEIN, READING_DATETIME,
      KWD, KWHD, KVARHD, KWR, KWHR, KVARHR, VAN, VBN, VCN, IAN, IBN, ICN, PF, ESTIMATION_FLAG, VERSION)
      VALUES(HIBERNATE_SEQUENCE.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    monthly: >
      INSERT INTO TXN_METER_DATA_MONTHLY (METER_DATA_ID, FILE_ID, SEIN, READING_DATETIME,
      KWD, KWHD, KVARHD, KWR, KWHR, KVARHR, VAN, VBN, VCN, IAN, IBN, ICN, PF, ESTIMATION_FLAG, VERSION)
      VALUES(HIBERNATE_SEQUENCE.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
bcq:
  manifest: >
    INSERT INTO TXN_BCQ_UPLOAD_FILE (FILE_ID, TRANSACTION_ID, FILE_NAME, FILE_SIZE, STATUS, SUBMITTED_DATE)
    VALUES (HIBERNATE_SEQUENCE.NEXTVAL, ?, ?, ?, ?, ?)
  data: >
    INSERT INTO TXN_BCQ_DATA (BCQ_DATA_ID, FILE_ID, SELLING_MTN, BUYING_PARTICIPANT_ID, REFERENCE_MTN, START_TIME,
    END_TIME, BCQ) VALUES (HIBERNATE_SEQUENCE.NEXTVAL, ?, ?, ?, ?, ?, ?, ?)
