spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crss_metering
    username: crss_metering
    password: crss_metering
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 20

server:
  port: 8084
  undertow:
    accesslog:
      dir: target
      enabled: true
      pattern: combined
  compression:
    enabled: true
    min-response-size: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #    healthcheck:
      #      enabled: true
    lease:
      duration: 5
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8082/oauth/access_token
      userAuthorizationUri: http://localhost:8082/oauth/authorize
      clientId: crss
      clientSecret: crsssecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
      access-token-validity-seconds: 3600
    resource:
      userInfoUri: http://localhost:8082/user

logging:
  level:
    com.pemc: DEBUG
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG
