spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crss_metering
    username: crss_metering
    password: crss_metering
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTimeout: 10000
      maximumPoolSize: 20
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    ports:
      - "5672:5672"
      - "15672:15672"

server:
  port: 8084
  undertow:
    accesslog:
      dir: target
      enabled: true
      pattern: combined
  compression:
    enabled: true
    min-response-size: 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #    healthcheck:
      #      enabled: true
#    lease:
#      duration: 5
#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8082/oauth/access_token
      userAuthorizationUri: http://localhost:8082/oauth/authorize
      clientId: crss
      clientSecret: crsssecret
      authorized-grant-types: authorization_code,refresh_token,password
      scope: openid
      access-token-validity-seconds: 3600
    resource:
      userInfoUri: http://localhost:8082/user

mq:
  manifest:
    header:
      insert: >
        INSERT INTO TXN_MQ_MANIFEST_HEADER (header_id, transaction_id, file_count, category,
        upload_by, upload_datetime) VALUES (NEXTVAL('MQ_MANIFEST_HEADER_SEQ'), ?, ?, ?, ?, ?)
      query: >
        SELECT HEADER_ID AS headerID, FILE_COUNT AS fileCount
        FROM TXN_MQ_MANIFEST_HEADER WHERE TRANSACTION_ID = :txnID AND TAIL_RECEIVED = 'Y'
    trailer: >
      UPDATE TXN_MQ_MANIFEST_HEADER SET tail_received = 'Y' WHERE transaction_id = ?
    file:
      insert: >
        INSERT INTO TXN_MQ_MANIFEST_FILE (file_id, header_id, transaction_id, filename, filetype,
        filesize, checksum, upload_datetime) VALUES (NEXTVAL('MQ_MANIFEST_FILE_SEQ'), ?, ?, ?, ?, ?, ?, ?)
      query: >
        SELECT A.FILE_ID as fileID,
               A.HEADER_ID AS headerID,
               A.TRANSACTION_ID AS transactionID,
               A.FILENAME,
               A.FILETYPE,
               A.FILESIZE,
               A.CHECKSUM,
               A.UPLOAD_DATETIME AS uploadDateTime,
               A.PROCESS_FLAG AS processFlag,
               A.STATUS,
               A.ERROR_DETAILS AS errorDetails
        FROM TXN_MQ_MANIFEST_FILE A INNER JOIN TXN_MQ_MANIFEST_HEADER B ON A.HEADER_ID = B.HEADER_ID
        WHERE B.TRANSACTION_ID = :txnID
    status: >
      UPDATE TXN_MQ_MANIFEST_FILE SET PROCESS_FLAG = 'Y', STATUS = :status, ERROR_DETAILS = :errorDetail WHERE FILE_ID = :fileID
  meter:
    daily: >
      INSERT INTO TXN_METER_DATA_DAILY VALUES(
      NEXTVAL('MQ_DATA_DAILY_SEQ'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    monthly: >
      INSERT INTO TXN_METER_DATA_MONTHLY VALUES(
      NEXTVAL('MQ_DATA_MONTHLY_SEQ'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
bcq:
  manifest: >
    INSERT INTO TXN_BCQ_UPLOAD_FILE (
      FILE_ID,
      TRANSACTION_ID,
      FILE_NAME,
      FILE_SIZE,
      SUBMITTED_DATE)
    VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?)
  header:
    insert: >
      INSERT INTO TXN_BCQ_HEADER (
        BCQ_HEADER_ID,
        FILE_ID,
        SELLING_MTN,
        BILLING_ID,
        BUYING_PARTICIPANT_NAME,
        BUYING_PARTICIPANT_SHORT_NAME,
        SELLING_PARTICIPANT_NAME,
        SELLING_PARTICIPANT_SHORT_NAME,
        STATUS,
        TRADING_DATE,
        DEADLINE_DATE)
      VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    update: >
      UPDATE TXN_BCQ_HEADER SET
        FILE_ID = ?
      WHERE SELLING_MTN = ? AND BILLING_ID = ? AND TRADING_DATE = ? AND SELLING_PARTICIPANT_SHORT_NAME = ?
    count: >
      SELECT COUNT(*) FROM TXN_BCQ_HEADER
      WHERE SELLING_MTN = ? AND BILLING_ID = ? AND TRADING_DATE = ? AND SELLING_PARTICIPANT_SHORT_NAME = ?
    id: >
      SELECT BCQ_HEADER_ID FROM TXN_BCQ_HEADER
      WHERE SELLING_MTN = ? AND BILLING_ID = ? AND TRADING_DATE = ? AND SELLING_PARTICIPANT_SHORT_NAME = ?
    status: >
      UPDATE TXN_BCQ_HEADER SET STATUS = ? WHERE BCQ_HEADER_ID = ?
  data:
    insert: >
      INSERT INTO TXN_BCQ_DATA (
        BCQ_DATA_ID,
        BCQ_HEADER_ID,
        REFERENCE_MTN,
        START_TIME,
        END_TIME,
        BCQ)
      VALUES (NEXTVAL('HIBERNATE_SEQUENCE'), ?, ?, ?, ?, ?)
    update: >
      UPDATE TXN_BCQ_DATA SET
        REFERENCE_MTN = ?,
        BCQ = ?
       WHERE END_TIME = ? AND BCQ_HEADER_ID = ?
    details: >
      SELECT
        REFERENCE_MTN,
        END_TIME,
        BCQ
      FROM TXN_BCQ_DATA
      WHERE BCQ_HEADER_ID = ?
  display:
    data: >
      SELECT
        BCQ_HEADER_ID,
        SELLING_MTN,
        BILLING_ID,
        BUYING_PARTICIPANT_NAME,
        BUYING_PARTICIPANT_SHORT_NAME,
        SELLING_PARTICIPANT_NAME,
        SELLING_PARTICIPANT_SHORT_NAME,
        TRADING_DATE,
        DEADLINE_DATE,
        TRANSACTION_ID,
        SUBMITTED_DATE,
        STATUS
      FROM TXN_BCQ_HEADER A INNER JOIN TXN_BCQ_UPLOAD_FILE B ON A.FILE_ID = B.FILE_ID
    count: >
      SELECT COUNT(*)
      FROM TXN_BCQ_HEADER A INNER JOIN TXN_BCQ_UPLOAD_FILE B ON A.FILE_ID = B.FILE_ID
    paginate: >
      {SELECT_QUERY} LIMIT ({PAGE_NO} + 1) * {PAGE_SIZE} OFFSET {PAGE_NO} * {PAGE_SIZE}