package com.pemc.crss.meter.upload;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;

import static javax.swing.JFileChooser.DIRECTORIES_ONLY;

public class HeaderPanel extends javax.swing.JPanel {

    /**
     * Creates new form HeaderPanel
     */
    public HeaderPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() { //GEN-BEGIN:initComponents
        GridBagConstraints gridBagConstraints;

        categoryComboBoxModel = new DefaultComboBoxModel<>(
            new String[]{
                "Daily", "Monthly", "Corrected Meter Data"
            }
        );
        mspComboBoxModel = new DefaultComboBoxModel<>(
            new String[]{
                "Manila Electric Company",
                "Ibaan Electric and Engineering Corporation",
                "National Grid Corporation of the Phils",
                "Peninsula Electric Cooperative",
                "Exemplar Enterprise Inc. (Puyat Flooring Products Inc.)"
            }
        );
        filetypeComboBoxModel = new DefaultComboBoxModel<>(
            new String[]{
                "XLS, XLSX", "CSV", "MDEF"
            }
        );
        toolbarPanel = new JPanel();
        btnSelectFiles = new JButton();
        btnUpload = new JButton();
        fieldPanel = new JPanel();
        lblCategory = new JLabel();
        cboCategory = new JComboBox<>();
        lblFileType = new JLabel();
        cboFileType = new JComboBox<>();
        lblMSP = new JLabel();
        cboMSP = new JComboBox<>();

        setLayout(new BorderLayout());

        btnSelectFiles.setIcon(new ImageIcon(getClass().getResource("/images/Transaction List Filled-50.png"))); // NOI18N
        btnSelectFiles.setToolTipText("Select Files");
        btnSelectFiles.setFocusable(false);
        btnSelectFiles.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSelectFiles.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnSelectFilesselectFilesActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnSelectFiles);

        btnUpload.setIcon(new ImageIcon(getClass().getResource("/images/Upload to the Cloud-50.png"))); // NOI18N
        btnUpload.setToolTipText("Upload Files");
        btnUpload.setFocusable(false);
        btnUpload.setHorizontalTextPosition(SwingConstants.CENTER);
        btnUpload.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnUploaduploadActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnUpload);

        add(toolbarPanel, BorderLayout.WEST);

        fieldPanel.setLayout(new GridBagLayout());

        lblCategory.setText("Category:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(lblCategory, gridBagConstraints);

        cboCategory.setModel(categoryComboBoxModel);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(cboCategory, gridBagConstraints);

        lblFileType.setText("File Type:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(lblFileType, gridBagConstraints);

        cboFileType.setModel(filetypeComboBoxModel);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.EAST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(cboFileType, gridBagConstraints);

        lblMSP.setText("MSP:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(lblMSP, gridBagConstraints);

        cboMSP.setModel(mspComboBoxModel);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(cboMSP, gridBagConstraints);

        add(fieldPanel, BorderLayout.EAST);
    } //GEN-END:initComponents

    private void btnSelectFilesselectFilesActionPerformed(ActionEvent evt) { //GEN-FIRST:event_btnSelectFilesselectFilesActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        fileChooser.setFileSelectionMode(DIRECTORIES_ONLY);
        fileChooser.showOpenDialog(this);
    } //GEN-LAST:event_btnSelectFilesselectFilesActionPerformed

    private void btnUploaduploadActionPerformed(ActionEvent evt) { //GEN-FIRST:event_btnUploaduploadActionPerformed
        // TODO:
        // 1. Display a progress bar
        // 2. Send files to the server
    } //GEN-LAST:event_btnUploaduploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnSelectFiles;
    private JButton btnUpload;
    private DefaultComboBoxModel categoryComboBoxModel;
    private JComboBox<String> cboCategory;
    private JComboBox<String> cboFileType;
    private JComboBox<String> cboMSP;
    private JPanel fieldPanel;
    private DefaultComboBoxModel filetypeComboBoxModel;
    private JLabel lblCategory;
    private JLabel lblFileType;
    private JLabel lblMSP;
    private DefaultComboBoxModel mspComboBoxModel;
    private JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables
}
