package com.pemc.crss.meter.upload;

import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

import static com.pemc.crss.meter.upload.LoginDialog.RET_OK;
import static com.pemc.crss.meter.upload.SelectedFileUtils.retrieveFileListing;
import static javax.swing.JFileChooser.APPROVE_OPTION;
import static javax.swing.JFileChooser.FILES_AND_DIRECTORIES;
import static org.apache.commons.lang3.StringUtils.equalsIgnoreCase;

public class HeaderPanel extends JPanel {

    private FileFilter fileFilterXLS = new FileNameExtensionFilter("Excel Files (xls, xlsx)",
            "xls", "xlsx");
    private FileFilter fileFilterMDEF = new FileNameExtensionFilter("MDEF Files (mde)",
            "mde");
    private FileFilter fileFilterCSV = new FileNameExtensionFilter("CSV Files (csv)",
            "csv");

    private MeterDataUploader parent;

    public HeaderPanel() {
        initComponents();
    }

    public void configureComponents(MeterDataUploader parent) {
        this.parent = parent;

        btnLogout.setVisible(false);

        cboCategory.addItem(new ComboBoxItem("DAILY", "Daily"));
        cboCategory.addItem(new ComboBoxItem("MONTHLY", "Monthly"));
        cboCategory.addItem(new ComboBoxItem("CORRECTED_DAILY", "Corrected Meter Data (Daily)"));
        cboCategory.addItem(new ComboBoxItem("CORRECTED_MONTHLY", "Corrected Meter Data (Monthly)"));
    }

    public void configureServices() {
        // TODO:
        // 0. Consider prepopulation of MSP via async call at startup
        // 1. Populate MSP combo box: Registration /category/msp
        // 2. MSP combo box should have a blank item as the first element
        // 3. Determine user type
        // 4. If MSP, change MSP combo box selection to corresponding logged in MSP and disable combo box
        // 5. If PEMC user, enable MSP combo box selection

        // 6. Upon clicking on upload the following validation should take place:
        // 6.1 there should be some files selected
        // 6.2 there should be an msp selected (if pemc user)
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        GridBagConstraints gridBagConstraints;

        mspComboBoxModel = new DefaultComboBoxModel<>(
            new String[]{
                "Manila Electric Company",
                "Ibaan Electric and Engineering Corporation",
                "National Grid Corporation of the Phils",
                "Peninsula Electric Cooperative",
                "Exemplar Enterprise Inc. (Puyat Flooring Products Inc.)"
            }
        );
        toolbarPanel = new JPanel();
        btnSelectFiles = new JButton();
        btnClearTable = new JButton();
        btnUpload = new JButton();
        btnSettings = new JButton();
        btnLogout = new JButton();
        btnLogin = new JButton();
        fieldPanel = new JPanel();
        lblCategory = new JLabel();
        cboCategory = new JComboBox<>();
        lblMSP = new JLabel();
        cboMSP = new JComboBox<>();

        setLayout(new BorderLayout());

        btnSelectFiles.setIcon(new ImageIcon(getClass().getResource("/images/Transaction List Filled-50.png"))); // NOI18N
        btnSelectFiles.setToolTipText("Select Files");
        btnSelectFiles.setEnabled(false);
        btnSelectFiles.setFocusable(false);
        btnSelectFiles.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSelectFiles.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                selectFilesActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnSelectFiles);

        btnClearTable.setIcon(new ImageIcon(getClass().getResource("/images/Broom-48.png"))); // NOI18N
        btnClearTable.setToolTipText("Clear Selection");
        btnClearTable.setEnabled(false);
        btnClearTable.setFocusable(false);
        btnClearTable.setHorizontalTextPosition(SwingConstants.CENTER);
        btnClearTable.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                clearSelectionActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnClearTable);

        btnUpload.setIcon(new ImageIcon(getClass().getResource("/images/Upload to the Cloud-50.png"))); // NOI18N
        btnUpload.setToolTipText("Upload Files");
        btnUpload.setEnabled(false);
        btnUpload.setFocusable(false);
        btnUpload.setHorizontalTextPosition(SwingConstants.CENTER);
        btnUpload.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnUpload);

        btnSettings.setIcon(new ImageIcon(getClass().getResource("/images/Vertical Settings Mixer-50.png"))); // NOI18N
        btnSettings.setToolTipText("Settings");
        btnSettings.setEnabled(false);
        btnSettings.setFocusable(false);
        btnSettings.setHorizontalTextPosition(SwingConstants.CENTER);
        btnSettings.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                settingsActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnSettings);

        btnLogout.setIcon(new ImageIcon(getClass().getResource("/images/Export-48.png"))); // NOI18N
        btnLogout.setToolTipText("Logout");
        btnLogout.setEnabled(false);
        btnLogout.setFocusable(false);
        btnLogout.setHorizontalTextPosition(SwingConstants.CENTER);
        btnLogout.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnLogout);

        btnLogin.setIcon(new ImageIcon(getClass().getResource("/images/Key-48.png"))); // NOI18N
        btnLogin.setToolTipText("Settings");
        btnLogin.setFocusable(false);
        btnLogin.setHorizontalTextPosition(SwingConstants.CENTER);
        btnLogin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        toolbarPanel.add(btnLogin);

        add(toolbarPanel, BorderLayout.WEST);

        fieldPanel.setLayout(new GridBagLayout());

        lblCategory.setText("Category:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(lblCategory, gridBagConstraints);

        cboCategory.setEnabled(false);
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(cboCategory, gridBagConstraints);

        lblMSP.setText("MSP:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(lblMSP, gridBagConstraints);

        cboMSP.setModel(mspComboBoxModel);
        cboMSP.setEnabled(false);
        cboMSP.setPreferredSize(new Dimension(350, 27));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        fieldPanel.add(cboMSP, gridBagConstraints);

        add(fieldPanel, BorderLayout.EAST);
    }//GEN-END:initComponents

    private void selectFilesActionPerformed(ActionEvent evt) {//GEN-FIRST:event_selectFilesActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        String selectedCategory = ((ComboBoxItem) cboCategory.getSelectedItem()).getValue();
        if (equalsIgnoreCase(selectedCategory, "DAILY")) {
            fileChooser.addChoosableFileFilter(fileFilterMDEF);
        }

        fileChooser.addChoosableFileFilter(fileFilterXLS);
        fileChooser.addChoosableFileFilter(fileFilterCSV);
        fileChooser.setAcceptAllFileFilterUsed(false);

        fileChooser.setFileHidingEnabled(true);
        fileChooser.setFileSelectionMode(FILES_AND_DIRECTORIES);
        fileChooser.setMultiSelectionEnabled(true);
        int action = fileChooser.showOpenDialog(this);

        if (action == APPROVE_OPTION) {
            FileNameExtensionFilter fileFilter = (FileNameExtensionFilter) fileChooser.getFileFilter();

            List<FileBean> selectedFiles = retrieveFileListing(fileChooser.getSelectedFiles(), fileFilter.getExtensions());
            parent.updateTableDisplay(selectedFiles);

            btnSelectFiles.setEnabled(false);
            btnClearTable.setEnabled(true);
            btnUpload.setEnabled(true);
        }
    }//GEN-LAST:event_selectFilesActionPerformed

    private void uploadActionPerformed(ActionEvent evt) {//GEN-FIRST:event_uploadActionPerformed
        // TODO:
        // 1. Create custom model for MSP
        // 2. Populate MSP combo box from rest call to registration module
        // 3. If user is an MSP, set the default combo box selection to the currently logged in user and
        //    disable the combo box

        // NOTE: selectedItem and selectedIndex are just temporary code
        String category = ((ComboBoxItem) cboCategory.getSelectedItem()).getValue();
        parent.uploadData(category, cboMSP.getSelectedIndex());
    }//GEN-LAST:event_uploadActionPerformed

    private void settingsActionPerformed(ActionEvent evt) {//GEN-FIRST:event_settingsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsActionPerformed

    private void clearSelectionActionPerformed(ActionEvent evt) {//GEN-FIRST:event_clearSelectionActionPerformed
        parent.clearSelectedFiles();

        btnSelectFiles.setEnabled(true);
        btnClearTable.setEnabled(false);
        btnUpload.setEnabled(false);
    }//GEN-LAST:event_clearSelectionActionPerformed

    private void logoutActionPerformed(ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        parent.logout();
        disableToolbar();
    }//GEN-LAST:event_logoutActionPerformed

    private void loginActionPerformed(ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        LoginDialog loginDialog = new LoginDialog(parent, true);
        loginDialog.setVisible(true);

        if (loginDialog.getReturnStatus() == RET_OK) {
            parent.login(loginDialog.getUsername(), loginDialog.getPassword());
        }
    }//GEN-LAST:event_loginActionPerformed

    public void enableToolbar() {
        btnSelectFiles.setEnabled(true);
        btnClearTable.setEnabled(false);
        btnUpload.setEnabled(false);
        btnSettings.setEnabled(true);

        btnLogin.setEnabled(false);
        btnLogin.setVisible(false);

        btnLogout.setEnabled(true);
        btnLogout.setVisible(true);

        cboCategory.setEnabled(true);
        cboMSP.setEnabled(true);
    }

    public void disableToolbar() {
        btnSelectFiles.setEnabled(false);
        btnClearTable.setEnabled(false);
        btnUpload.setEnabled(false);
        btnSettings.setEnabled(false);

        btnLogin.setEnabled(true);
        btnLogin.setVisible(true);

        btnLogout.setEnabled(false);
        btnLogout.setVisible(false);

        cboCategory.setEnabled(false);
        cboMSP.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnClearTable;
    private JButton btnLogin;
    private JButton btnLogout;
    private JButton btnSelectFiles;
    private JButton btnSettings;
    private JButton btnUpload;
    private JComboBox<ComboBoxItem> cboCategory;
    private JComboBox<String> cboMSP;
    private JPanel fieldPanel;
    private JLabel lblCategory;
    private JLabel lblMSP;
    private DefaultComboBoxModel mspComboBoxModel;
    private JPanel toolbarPanel;
    // End of variables declaration//GEN-END:variables
}
