package com.pemc.crss.meter.upload;

import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.WindowConstants;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import static java.awt.event.KeyEvent.VK_ESCAPE;
import javax.swing.ImageIcon;
import static javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT;

public class LoginDialog extends JDialog {

    public static final int RET_CANCEL = 0;

    public static final int RET_OK = 1;

    public LoginDialog(Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);

        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        GridBagConstraints gridBagConstraints;

        headerPanel = new JPanel();
        lblSecurityTitle = new JLabel();
        lblSecurityIcon = new JLabel();
        fieldPanel = new JPanel();
        lblMessage = new JLabel();
        errorMessage = new JLabel();
        lblUsername = new JLabel();
        txtUsername = new JTextField();
        lblPassword = new JLabel();
        txtPassword = new JPasswordField();
        buttonPanel = new JPanel();
        btnLogin = new JButton();
        btnCancel = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setPreferredSize(new Dimension(400, 300));
        setResizable(false);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                closeDialog(evt);
            }
        });

        headerPanel.setBackground(new Color(186, 186, 186));
        headerPanel.setLayout(new GridBagLayout());

        lblSecurityTitle.setFont(new Font("Lucida Grande", 0, 24)); // NOI18N
        lblSecurityTitle.setText("Security Check");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(0, 0, 0, 50);
        headerPanel.add(lblSecurityTitle, gridBagConstraints);

        lblSecurityIcon.setIcon(new ImageIcon(getClass().getResource("/images/Security Checked-96.png"))); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(0, 50, 0, 0);
        headerPanel.add(lblSecurityIcon, gridBagConstraints);

        getContentPane().add(headerPanel, BorderLayout.NORTH);

        fieldPanel.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createEmptyBorder(5, 1, 1, 1), BorderFactory.createEtchedBorder()));
        fieldPanel.setLayout(new GridBagLayout());

        lblMessage.setText("Login with your CRSS application credentails");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        fieldPanel.add(lblMessage, gridBagConstraints);

        errorMessage.setForeground(Color.red);
        errorMessage.setMinimumSize(new Dimension(30, 16));
        errorMessage.setPreferredSize(new Dimension(30, 16));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        fieldPanel.add(errorMessage, gridBagConstraints);

        lblUsername.setText("Username:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        fieldPanel.add(lblUsername, gridBagConstraints);

        txtUsername.setMinimumSize(new Dimension(200, 26));
        txtUsername.setPreferredSize(new Dimension(200, 26));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        fieldPanel.add(txtUsername, gridBagConstraints);

        lblPassword.setText("Password:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        fieldPanel.add(lblPassword, gridBagConstraints);

        txtPassword.setMinimumSize(new Dimension(200, 26));
        txtPassword.setPreferredSize(new Dimension(200, 26));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = GridBagConstraints.WEST;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        fieldPanel.add(txtPassword, gridBagConstraints);

        getContentPane().add(fieldPanel, BorderLayout.CENTER);

        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnLogin.setText("Login");
        btnLogin.setPreferredSize(new Dimension(100, 29));
        btnLogin.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        buttonPanel.add(btnLogin);
        getRootPane().setDefaultButton(btnLogin);

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new Dimension(100, 29));
        btnCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCancel);

        getContentPane().add(buttonPanel, BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void okActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_okActionPerformed

    private void cancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelActionPerformed

    private void closeDialog(WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    public String getUsername() {
        return txtUsername.getText();
    }

    public String getPassword() {
        return new String(txtPassword.getPassword());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCancel;
    private JButton btnLogin;
    private JPanel buttonPanel;
    private JLabel errorMessage;
    private JPanel fieldPanel;
    private JPanel headerPanel;
    private JLabel lblMessage;
    private JLabel lblPassword;
    private JLabel lblSecurityIcon;
    private JLabel lblSecurityTitle;
    private JLabel lblUsername;
    private JPasswordField txtPassword;
    private JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
