package com.pemc.crss.meter.upload;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.border.SoftBevelBorder;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.FlowLayout;
import java.util.logging.Logger;

import static java.util.logging.Level.SEVERE;

public class MeterDataUploader extends JFrame {

    public MeterDataUploader() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() { //GEN-BEGIN:initComponents

        headerPanel = new HeaderPanel();
        tablePanel = new TablePanel();
        statusBarPanel = new JPanel();
        temporaryOAuthPanel = new JPanel();
        lblOAuth = new JLabel();
        txtOAuth = new JTextField();
        uploadStatusPanel = new JPanel();
        lblUploadStatus = new JLabel();
        uploadProgress = new JProgressBar();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meter Quantity Uploader");
        setMinimumSize(new Dimension(700, 550));
        setPreferredSize(new Dimension(700, 550));
        setResizable(false);
        getContentPane().add(headerPanel, BorderLayout.NORTH);
        getContentPane().add(tablePanel, BorderLayout.CENTER);

        statusBarPanel.setLayout(new BorderLayout());

        lblOAuth.setText("OAuth Token:");
        temporaryOAuthPanel.add(lblOAuth);

        txtOAuth.setPreferredSize(new Dimension(400, 26));
        temporaryOAuthPanel.add(txtOAuth);

        statusBarPanel.add(temporaryOAuthPanel, BorderLayout.CENTER);

        uploadStatusPanel.setBorder(new SoftBevelBorder(BevelBorder.LOWERED));
        uploadStatusPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 0));

        lblUploadStatus.setText("Uploading");
        uploadStatusPanel.add(lblUploadStatus);

        uploadProgress.setPreferredSize(new Dimension(300, 20));
        uploadStatusPanel.add(uploadProgress);

        statusBarPanel.add(uploadStatusPanel, BorderLayout.SOUTH);

        getContentPane().add(statusBarPanel, BorderLayout.SOUTH);

        setSize(new Dimension(960, 505));
        setLocationRelativeTo(null);
    } //GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MeterDataUploader.class.getName()).log(SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeterDataUploader().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private HeaderPanel headerPanel;
    private JLabel lblOAuth;
    private JLabel lblUploadStatus;
    private JPanel statusBarPanel;
    private TablePanel tablePanel;
    private JPanel temporaryOAuthPanel;
    private JTextField txtOAuth;
    private JProgressBar uploadProgress;
    private JPanel uploadStatusPanel;
    // End of variables declaration//GEN-END:variables
}
