package com.pemc.crss.meter.upload;

import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.BorderFactory;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.WindowConstants;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import static java.awt.event.KeyEvent.VK_ESCAPE;
import static javax.swing.JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT;

public class SettingsDialog extends JDialog {

    public static final int RET_CANCEL = 0;
    public static final int RET_SAVE = 1;

    private int returnStatus = RET_CANCEL;

    private MeterDataUploader parent;

    public SettingsDialog(MeterDataUploader parent, boolean modal) {
        super(parent, modal);

        this.parent = parent;
        initComponents();
        setLocationRelativeTo(parent);

        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    public void configureComponents() {
        txtServerURL.setText(parent.getProperty("URL"));
    }

    public int getReturnStatus() {
        return returnStatus;
    }

    public String getServerURL() {
        return txtServerURL.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        GridBagConstraints gridBagConstraints;

        contentPanel = new JPanel();
        lblServerURL = new JLabel();
        txtServerURL = new JTextField();
        buttonPanel = new JPanel();
        btnSave = new JButton();
        btnCancel = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent evt) {
                closeDialog(evt);
            }
        });

        contentPanel.setBorder(BorderFactory.createEtchedBorder());
        contentPanel.setLayout(new GridBagLayout());

        lblServerURL.setText("Server URL:");
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        contentPanel.add(lblServerURL, gridBagConstraints);

        txtServerURL.setPreferredSize(new Dimension(200, 26));
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new Insets(5, 5, 5, 5);
        contentPanel.add(txtServerURL, gridBagConstraints);

        getContentPane().add(contentPanel, BorderLayout.CENTER);

        buttonPanel.setLayout(new FlowLayout(FlowLayout.RIGHT));

        btnSave.setText("OK");
        btnSave.setPreferredSize(new Dimension(100, 29));
        btnSave.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        buttonPanel.add(btnSave);
        getRootPane().setDefaultButton(btnSave);

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new Dimension(100, 29));
        btnCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        buttonPanel.add(btnCancel);

        getContentPane().add(buttonPanel, BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents

    private void saveActionPerformed(ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        doClose(RET_SAVE);
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelActionPerformed

    private void closeDialog(WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog
    
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnCancel;
    private JButton btnSave;
    private JPanel buttonPanel;
    private JPanel contentPanel;
    private JLabel lblServerURL;
    private JTextField txtServerURL;
    // End of variables declaration//GEN-END:variables

}
