#spring:
#  profiles.active: dev

#---
#spring:
#  profiles: dev
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com.netflix: DEBUG
    org.springframework.cloud: DEBUG
