package com.pemc.crss.metering.constants;

public enum BcqEventCode {

    NTF_BCQ_SUBMIT_BUYER,
    NTF_BCQ_SUBMIT_SELLER,
    NTF_BCQ_VALIDATION_SELLER,
    NTF_BCQ_VALIDATION_DEPT,
    NTF_BCQ_CANCEL_BUYER,
    NTF_BCQ_CONFIRM_SELLER,
    NTF_BCQ_NULLIFY_SELLER,
    NTF_BCQ_UPDATE_BUYER,
    NTF_BCQ_UNCONFIRMED_SELLER,
    NTF_BCQ_UNCONFIRMED_BUYER,
    NTF_BCQ_UNNULLIFIED_SELLER,
    NTF_BCQ_UNNULLIFIED_BUYER,
    NTF_BCQ_SETTLEMENT_UPDATE_DEPT,
    NTF_BCQ_SETTLEMENT_NEW_DEPT,
    NTF_BCQ_SETTLEMENT_VALIDATION_DEPT,
    NTF_BCQ_REQUEST_CANCEL_DEPT,
    NTF_BCQ_APPROVE_UPDATE_SELLER,
    NTF_BCQ_APPROVE_UPDATE_BUYER,
    NTF_BCQ_APPROVE_NEW_SELLER,
    NTF_BCQ_APPROVE_NEW_BUYER,
    NTF_BCQ_APPROVE_CANCEL_SELLER,
    NTF_BCQ_APPROVE_CANCEL_BUYER

}
