package com.pemc.crss.metering.constants;

public enum BcqEventCode {

    NTF_BCQ_SUBMIT_BUYER,
    NTF_BCQ_SUBMIT_SELLER,
    NTF_BCQ_VALIDATION_SELLER,
    NTF_BCQ_VALIDATION_DEPT,
    NTF_BCQ_CANCEL_BUYER,
    NTF_BCQ_CONFIRM_SELLER,
    NTF_BCQ_NULLIFY_SELLER

}
