create table CRSS_METERING.txn_bcq_header(header_id number(38,0), billing_id varchar2(50), file_id number(38,0), selling_mtn varchar2(255), buying_participant_name varchar2(255), buying_participant_short_name varchar2(255), selling_participant_name varchar2(255), selling_participant_short_name varchar2(255), status varchar2(30), trading_date timestamp, deadline_date timestamp, updated_via varchar2(50), created_date timestamp, modified_date timestamp, constraint txn_bcq_headerpk primary key(header_id));

create table CRSS_METERING.txn_bcq_data(data_id number(38,0), header_id number(38,0), reference_mtn varchar2(255), start_time timestamp, end_time timestamp, bcq number(28,9), CONSTRAINT txn_bcq_datapk primary key(data_id));

create table CRSS_METERING.txn_bcq_upload_file(file_id number(38,0), transaction_id varchar2(36), file_name varchar2(255), file_size number(38,0), submitted_date timestamp, validation_status varchar2(8), constraint txn_bcq_upload_filepk primary key(file_id));

create table CRSS_METERING.txn_mq_manifest_header(header_id number(38,0), transaction_id varchar2(36),file_count number(10,0), category varchar2(20), notification_sent char(1), notification_datetime timestamp, tail_received char(1), upload_by varchar2(100), upload_datetime timestamp, msp_shortname varchar2(50), constraint txn_mq_manifest_headerpk primary key(header_id));

create table CRSS_METERING.txn_mq_manifest_file(file_id number(38,0), header_id number(38,0), transaction_id varchar2(36), filename varchar2(100), filetype varchar2(5), filesize number(38,0), checksum varchar2(36), upload_datetime timestamp, process_datetime timestamp, process_flag char(1), status varchar2(10), error_details varchar2(500), constraint txn_mq_manifest_filepk primary key(file_id));

create table CRSS_METERING.txn_meter_data_daily(meter_data_id number(38,0), file_id number(38,0), msp_shortname varchar2(50), category varchar2(20), sein varchar2(20), interval number(10,0), reading_datetime number(38,0), kwd numeric(25,17), kwd_channel_status number(10,0), kwd_interval_status number(10,0), kwhd numeric(25,17), kwhd_channel_status number(10,0), kwhd_interval_status number(10,0), kvarhd numeric(25,17), kvarhd_channel_status number(10,0), kvarhd_interval_status number(10,0), kwr numeric(25,17), kwr_channel_status number(10,0), kwr_interval_status number(10,0), kwhr numeric(25,17), kwhr_channel_status number(10,0), kwhr_interval_status number(10,0), kvarhr numeric(25,17), kvarhr_channel_status number(10,0), kvarhr_interval_status number(10,0), van numeric(25,17), van_channel_status number(10,0), van_interval_status number(10,0), vbn numeric(25,17), vbn_channel_status number(10,0), vbn_interval_status number(10,0), vcn numeric(25,17), vcn_channel_status number(10,0), vcn_interval_status number(10,0), ian numeric(25,17), ian_channel_status number(10,0), ian_interval_status number(10,0), ibn numeric(25,17), ibn_channel_status number(10,0), ibn_interval_status number(10,0), icn numeric(25,17), icn_channel_status number(10,0), icn_interval_status number(10,0), pf numeric(25,17), pf_channel_status number(10,0), pf_interval_status number(10,0), estimation_flag varchar2(15), created_date_time timestamp, consumed char(1), constraint txn_meter_data_dailypk primary key(meter_data_id));

create table CRSS_METERING.txn_meter_data_monthly(meter_data_id number(38,0), file_id number(38,0), msp_shortname varchar2(50), category varchar2(20), sein varchar2(20), interval number(10,0), reading_datetime number(38,0), kwd numeric(25,17), kwd_channel_status number(10,0), kwd_interval_status number(10,0), kwhd numeric(25,17), kwhd_channel_status number(10,0), kwhd_interval_status number(10,0), kvarhd numeric(25,17), kvarhd_channel_status number(10,0), kvarhd_interval_status number(10,0), kwr numeric(25,17), kwr_channel_status number(10,0), kwr_interval_status number(10,0), kwhr numeric(25,17), kwhr_channel_status number(10,0), kwhr_interval_status number(10,0), kvarhr numeric(25,17), kvarhr_channel_status number(10,0), kvarhr_interval_status number(10,0), van numeric(25,17), van_channel_status number(10,0), van_interval_status number(10,0), vbn numeric(25,17), vbn_channel_status number(10,0), vbn_interval_status number(10,0), vcn numeric(25,17), vcn_channel_status number(10,0), vcn_interval_status number(10,0), ian numeric(25,17), ian_channel_status number(10,0), ian_interval_status number(10,0), ibn numeric(25,17), ibn_channel_status number(10,0), ibn_interval_status number(10,0), icn numeric(25,17), icn_channel_status number(10,0), icn_interval_status number(10,0), pf numeric(25,17), pf_channel_status number(10,0), pf_interval_status number(10,0), estimation_flag varchar2(15), created_date_time timestamp, consumed char(1), constraint txn_meter_data_monthlypk primary key(meter_data_id));
